[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[[example]]
name = "encoding"

[[example]]
name = "encryption"

[[example]]
name = "hashing"

[[example]]
name = "padding"

[dependencies]
