use crate::bits::Bits;
use crate::enums::Bit::{self, One, Zero};

mod des_decrypt;
mod des_encrypt;
//mod triple_des_decrypt;
//mod triple_des_encrypt;

pub use des_decrypt::DesDecrypt;
pub use des_encrypt::DesEncrypt;
//pub use triple_des_decrypt::TripleDesDecrypt;
//pub use triple_des_encrypt::TripleDesEncrypt;

// initial permutation
const IP: [usize; 64] = [
    57, 49, 41, 33, 25, 17, 9, 1, 59, 51, 43, 35, 27, 19, 11, 3, 61, 53, 45, 37, 29, 21, 13, 5, 63,
    55, 47, 39, 31, 23, 15, 7, 56, 48, 40, 32, 24, 16, 8, 0, 58, 50, 42, 34, 26, 18, 10, 2, 60, 52,
    44, 36, 28, 20, 12, 4, 62, 54, 46, 38, 30, 22, 14, 6,
];

// final permutation
const FP: [usize; 64] = [
    39, 7, 47, 15, 55, 23, 63, 31, 38, 6, 46, 14, 54, 22, 62, 30, 37, 5, 45, 13, 53, 21, 61, 29,
    36, 4, 44, 12, 52, 20, 60, 28, 35, 3, 43, 11, 51, 19, 59, 27, 34, 2, 42, 10, 50, 18, 58, 26,
    33, 1, 41, 9, 49, 17, 57, 25, 32, 0, 40, 8, 48, 16, 56, 24,
];

const E: [usize; 48] = [
    31, 0, 1, 2, 3, 4, 3, 4, 5, 6, 7, 8, 7, 8, 9, 10, 11, 12, 11, 12, 13, 14, 15, 16, 15, 16, 17,
    18, 19, 20, 19, 20, 21, 22, 23, 24, 23, 24, 25, 26, 27, 28, 27, 28, 29, 30, 31, 0,
];

const P: [usize; 32] = [
    15, 6, 19, 20, 28, 11, 27, 16, 0, 14, 22, 25, 4, 17, 30, 9, 1, 7, 23, 13, 31, 26, 2, 8, 18, 12,
    29, 5, 21, 10, 3, 24,
];

// permuted choice 1
const PC1: [usize; 56] = [
    56, 48, 40, 32, 24, 16, 8, 0, 57, 49, 41, 33, 25, 17, 9, 1, 58, 50, 42, 34, 26, 18, 10, 2, 59,
    51, 43, 35, 62, 54, 46, 38, 30, 22, 14, 6, 61, 53, 45, 37, 29, 21, 13, 5, 60, 52, 44, 36, 28,
    20, 12, 4, 27, 19, 11, 3,
];

// permuted choice 2 array
const PC2_ARRAY: [[usize; 48]; 16] = [
    [
        14, 17, 11, 24, 1, 5, 3, 0, 15, 6, 21, 10, 23, 19, 12, 4, 26, 8, 16, 7, 27, 20, 13, 2, 41,
        52, 31, 37, 47, 55, 30, 40, 51, 45, 33, 48, 44, 49, 39, 28, 34, 53, 46, 42, 50, 36, 29, 32,
    ],
    [
        15, 18, 12, 25, 2, 6, 4, 1, 16, 7, 22, 11, 24, 20, 13, 5, 27, 9, 17, 8, 0, 21, 14, 3, 42,
        53, 32, 38, 48, 28, 31, 41, 52, 46, 34, 49, 45, 50, 40, 29, 35, 54, 47, 43, 51, 37, 30, 33,
    ],
    [
        17, 20, 14, 27, 4, 8, 6, 3, 18, 9, 24, 13, 26, 22, 15, 7, 1, 11, 19, 10, 2, 23, 16, 5, 44,
        55, 34, 40, 50, 30, 33, 43, 54, 48, 36, 51, 47, 52, 42, 31, 37, 28, 49, 45, 53, 39, 32, 35,
    ],
    [
        19, 22, 16, 1, 6, 10, 8, 5, 20, 11, 26, 15, 0, 24, 17, 9, 3, 13, 21, 12, 4, 25, 18, 7, 46,
        29, 36, 42, 52, 32, 35, 45, 28, 50, 38, 53, 49, 54, 44, 33, 39, 30, 51, 47, 55, 41, 34, 37,
    ],
    [
        21, 24, 18, 3, 8, 12, 10, 7, 22, 13, 0, 17, 2, 26, 19, 11, 5, 15, 23, 14, 6, 27, 20, 9, 48,
        31, 38, 44, 54, 34, 37, 47, 30, 52, 40, 55, 51, 28, 46, 35, 41, 32, 53, 49, 29, 43, 36, 39,
    ],
    [
        23, 26, 20, 5, 10, 14, 12, 9, 24, 15, 2, 19, 4, 0, 21, 13, 7, 17, 25, 16, 8, 1, 22, 11, 50,
        33, 40, 46, 28, 36, 39, 49, 32, 54, 42, 29, 53, 30, 48, 37, 43, 34, 55, 51, 31, 45, 38, 41,
    ],
    [
        25, 0, 22, 7, 12, 16, 14, 11, 26, 17, 4, 21, 6, 2, 23, 15, 9, 19, 27, 18, 10, 3, 24, 13,
        52, 35, 42, 48, 30, 38, 41, 51, 34, 28, 44, 31, 55, 32, 50, 39, 45, 36, 29, 53, 33, 47, 40,
        43,
    ],
    [
        27, 2, 24, 9, 14, 18, 16, 13, 0, 19, 6, 23, 8, 4, 25, 17, 11, 21, 1, 20, 12, 5, 26, 15, 54,
        37, 44, 50, 32, 40, 43, 53, 36, 30, 46, 33, 29, 34, 52, 41, 47, 38, 31, 55, 35, 49, 42, 45,
    ],
    [
        0, 3, 25, 10, 15, 19, 17, 14, 1, 20, 7, 24, 9, 5, 26, 18, 12, 22, 2, 21, 13, 6, 27, 16, 55,
        38, 45, 51, 33, 41, 44, 54, 37, 31, 47, 34, 30, 35, 53, 42, 48, 39, 32, 28, 36, 50, 43, 46,
    ],
    [
        2, 5, 27, 12, 17, 21, 19, 16, 3, 22, 9, 26, 11, 7, 0, 20, 14, 24, 4, 23, 15, 8, 1, 18, 29,
        40, 47, 53, 35, 43, 46, 28, 39, 33, 49, 36, 32, 37, 55, 44, 50, 41, 34, 30, 38, 52, 45, 48,
    ],
    [
        4, 7, 1, 14, 19, 23, 21, 18, 5, 24, 11, 0, 13, 9, 2, 22, 16, 26, 6, 25, 17, 10, 3, 20, 31,
        42, 49, 55, 37, 45, 48, 30, 41, 35, 51, 38, 34, 39, 29, 46, 52, 43, 36, 32, 40, 54, 47, 50,
    ],
    [
        6, 9, 3, 16, 21, 25, 23, 20, 7, 26, 13, 2, 15, 11, 4, 24, 18, 0, 8, 27, 19, 12, 5, 22, 33,
        44, 51, 29, 39, 47, 50, 32, 43, 37, 53, 40, 36, 41, 31, 48, 54, 45, 38, 34, 42, 28, 49, 52,
    ],
    [
        8, 11, 5, 18, 23, 27, 25, 22, 9, 0, 15, 4, 17, 13, 6, 26, 20, 2, 10, 1, 21, 14, 7, 24, 35,
        46, 53, 31, 41, 49, 52, 34, 45, 39, 55, 42, 38, 43, 33, 50, 28, 47, 40, 36, 44, 30, 51, 54,
    ],
    [
        10, 13, 7, 20, 25, 1, 27, 24, 11, 2, 17, 6, 19, 15, 8, 0, 22, 4, 12, 3, 23, 16, 9, 26, 37,
        48, 55, 33, 43, 51, 54, 36, 47, 41, 29, 44, 40, 45, 35, 52, 30, 49, 42, 38, 46, 32, 53, 28,
    ],
    [
        12, 15, 9, 22, 27, 3, 1, 26, 13, 4, 19, 8, 21, 17, 10, 2, 24, 6, 14, 5, 25, 18, 11, 0, 39,
        50, 29, 35, 45, 53, 28, 38, 49, 43, 31, 46, 42, 47, 37, 54, 32, 51, 44, 40, 48, 34, 55, 30,
    ],
    [
        13, 16, 10, 23, 0, 4, 2, 27, 14, 5, 20, 9, 22, 18, 11, 3, 25, 7, 15, 6, 26, 19, 12, 1, 40,
        51, 30, 36, 46, 54, 29, 39, 50, 44, 32, 47, 43, 48, 38, 55, 33, 52, 45, 41, 49, 35, 28, 31,
    ],
];

fn s_boxes(input: &Bits) -> Bits {
    let mut result = vec![];

    for (box_index, chunk) in input.chunks(6).enumerate() {
        // bits to uzise
        let bits = Bits::new(chunk);
        let s_box = S_BOXES[box_index];

        let substituted_bits = bits.substitution(s_box);
        result.extend_from_slice(&substituted_bits);
    }
    Bits::new(result)
}

const S_BOXES: [[[Bit; 4]; 64]; 8] = [
    [
        [One, One, One, Zero],
        [Zero, Zero, Zero, Zero],
        [Zero, One, Zero, Zero],
        [One, One, One, One],
        [One, One, Zero, One],
        [Zero, One, One, One],
        [Zero, Zero, Zero, One],
        [Zero, One, Zero, Zero],
        [Zero, Zero, One, Zero],
        [One, One, One, Zero],
        [One, One, One, One],
        [Zero, Zero, One, Zero],
        [One, Zero, One, One],
        [One, One, Zero, One],
        [One, Zero, Zero, Zero],
        [Zero, Zero, Zero, One],
        [Zero, Zero, One, One],
        [One, Zero, One, Zero],
        [One, Zero, One, Zero],
        [Zero, One, One, Zero],
        [Zero, One, One, Zero],
        [One, One, Zero, Zero],
        [One, One, Zero, Zero],
        [One, Zero, One, One],
        [Zero, One, Zero, One],
        [One, Zero, Zero, One],
        [One, Zero, Zero, One],
        [Zero, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [Zero, Zero, One, One],
        [Zero, One, One, One],
        [One, Zero, Zero, Zero],
        [Zero, One, Zero, Zero],
        [One, One, One, One],
        [Zero, Zero, Zero, One],
        [One, One, Zero, Zero],
        [One, One, One, Zero],
        [One, Zero, Zero, Zero],
        [One, Zero, Zero, Zero],
        [Zero, Zero, One, Zero],
        [One, One, Zero, One],
        [Zero, One, Zero, Zero],
        [Zero, One, One, Zero],
        [One, Zero, Zero, One],
        [Zero, Zero, One, Zero],
        [Zero, Zero, Zero, One],
        [One, Zero, One, One],
        [Zero, One, One, One],
        [One, One, One, One],
        [Zero, One, Zero, One],
        [One, One, Zero, Zero],
        [One, Zero, One, One],
        [One, Zero, Zero, One],
        [Zero, Zero, One, One],
        [Zero, One, One, One],
        [One, One, One, Zero],
        [Zero, Zero, One, One],
        [One, Zero, One, Zero],
        [One, Zero, One, Zero],
        [Zero, Zero, Zero, Zero],
        [Zero, One, Zero, One],
        [Zero, One, One, Zero],
        [Zero, Zero, Zero, Zero],
        [One, One, Zero, One],
    ],
    [
        [One, One, One, One],
        [Zero, Zero, One, One],
        [Zero, Zero, Zero, One],
        [One, One, Zero, One],
        [One, Zero, Zero, Zero],
        [Zero, One, Zero, Zero],
        [One, One, One, Zero],
        [Zero, One, One, One],
        [Zero, One, One, Zero],
        [One, One, One, One],
        [One, Zero, One, One],
        [Zero, Zero, One, Zero],
        [Zero, Zero, One, One],
        [One, Zero, Zero, Zero],
        [Zero, One, Zero, Zero],
        [One, One, One, Zero],
        [One, Zero, Zero, One],
        [One, One, Zero, Zero],
        [Zero, One, One, One],
        [Zero, Zero, Zero, Zero],
        [Zero, Zero, One, Zero],
        [Zero, Zero, Zero, One],
        [One, One, Zero, One],
        [One, Zero, One, Zero],
        [One, One, Zero, Zero],
        [Zero, One, One, Zero],
        [Zero, Zero, Zero, Zero],
        [One, Zero, Zero, One],
        [Zero, One, Zero, One],
        [One, Zero, One, One],
        [One, Zero, One, Zero],
        [Zero, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [One, One, Zero, One],
        [One, One, One, Zero],
        [One, Zero, Zero, Zero],
        [Zero, One, One, One],
        [One, Zero, One, Zero],
        [One, Zero, One, One],
        [Zero, Zero, Zero, One],
        [One, Zero, One, Zero],
        [Zero, Zero, One, One],
        [Zero, One, Zero, Zero],
        [One, One, One, One],
        [One, One, Zero, One],
        [Zero, One, Zero, Zero],
        [Zero, Zero, Zero, One],
        [Zero, Zero, One, Zero],
        [Zero, One, Zero, One],
        [One, Zero, One, One],
        [One, Zero, Zero, Zero],
        [Zero, One, One, Zero],
        [One, One, Zero, Zero],
        [Zero, One, One, One],
        [Zero, One, One, Zero],
        [One, One, Zero, Zero],
        [One, Zero, Zero, One],
        [Zero, Zero, Zero, Zero],
        [Zero, Zero, One, One],
        [Zero, One, Zero, One],
        [Zero, Zero, One, Zero],
        [One, One, One, Zero],
        [One, One, One, One],
        [One, Zero, Zero, One],
    ],
    [
        [One, Zero, One, Zero],
        [One, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [Zero, One, One, One],
        [One, Zero, Zero, One],
        [Zero, Zero, Zero, Zero],
        [One, One, One, Zero],
        [One, Zero, Zero, One],
        [Zero, One, One, Zero],
        [Zero, Zero, One, One],
        [Zero, Zero, One, One],
        [Zero, One, Zero, Zero],
        [One, One, One, One],
        [Zero, One, One, Zero],
        [Zero, One, Zero, One],
        [One, Zero, One, Zero],
        [Zero, Zero, Zero, One],
        [Zero, Zero, One, Zero],
        [One, One, Zero, One],
        [One, Zero, Zero, Zero],
        [One, One, Zero, Zero],
        [Zero, One, Zero, One],
        [Zero, One, One, One],
        [One, One, One, Zero],
        [One, Zero, One, One],
        [One, One, Zero, Zero],
        [Zero, One, Zero, Zero],
        [One, Zero, One, One],
        [Zero, Zero, One, Zero],
        [One, One, One, One],
        [One, Zero, Zero, Zero],
        [Zero, Zero, Zero, One],
        [One, One, Zero, One],
        [Zero, Zero, Zero, One],
        [Zero, One, One, Zero],
        [One, Zero, One, Zero],
        [Zero, One, Zero, Zero],
        [One, One, Zero, One],
        [One, Zero, Zero, One],
        [Zero, Zero, Zero, Zero],
        [One, Zero, Zero, Zero],
        [Zero, One, One, Zero],
        [One, One, One, One],
        [One, Zero, Zero, One],
        [Zero, Zero, One, One],
        [One, Zero, Zero, Zero],
        [Zero, Zero, Zero, Zero],
        [Zero, One, One, One],
        [One, Zero, One, One],
        [Zero, One, Zero, Zero],
        [Zero, Zero, Zero, One],
        [One, One, One, One],
        [Zero, Zero, One, Zero],
        [One, One, One, Zero],
        [One, One, Zero, Zero],
        [Zero, Zero, One, One],
        [Zero, One, Zero, One],
        [One, Zero, One, One],
        [One, Zero, One, Zero],
        [Zero, One, Zero, One],
        [One, One, One, Zero],
        [Zero, Zero, One, Zero],
        [Zero, One, One, One],
        [One, One, Zero, Zero],
    ],
    [
        [Zero, One, One, One],
        [One, One, Zero, One],
        [One, One, Zero, One],
        [One, Zero, Zero, Zero],
        [One, One, One, Zero],
        [One, Zero, One, One],
        [Zero, Zero, One, One],
        [Zero, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [Zero, One, One, Zero],
        [Zero, One, One, Zero],
        [One, One, One, One],
        [One, Zero, Zero, One],
        [Zero, Zero, Zero, Zero],
        [One, Zero, One, Zero],
        [Zero, Zero, One, One],
        [Zero, Zero, Zero, One],
        [Zero, One, Zero, Zero],
        [Zero, Zero, One, Zero],
        [Zero, One, One, One],
        [One, Zero, Zero, Zero],
        [Zero, Zero, One, Zero],
        [Zero, One, Zero, One],
        [One, One, Zero, Zero],
        [One, Zero, One, One],
        [Zero, Zero, Zero, One],
        [One, One, Zero, Zero],
        [One, Zero, One, Zero],
        [Zero, One, Zero, Zero],
        [One, One, One, Zero],
        [One, One, One, One],
        [One, Zero, Zero, One],
        [One, Zero, One, Zero],
        [Zero, Zero, One, One],
        [Zero, One, One, Zero],
        [One, One, One, One],
        [One, Zero, Zero, One],
        [Zero, Zero, Zero, Zero],
        [Zero, Zero, Zero, Zero],
        [Zero, One, One, Zero],
        [One, One, Zero, Zero],
        [One, Zero, One, Zero],
        [One, Zero, One, One],
        [Zero, Zero, Zero, One],
        [Zero, One, One, One],
        [One, One, Zero, One],
        [One, One, Zero, One],
        [One, Zero, Zero, Zero],
        [One, One, One, One],
        [One, Zero, Zero, One],
        [Zero, Zero, Zero, One],
        [Zero, One, Zero, Zero],
        [Zero, Zero, One, One],
        [Zero, One, Zero, One],
        [One, One, One, Zero],
        [One, Zero, One, One],
        [Zero, One, Zero, One],
        [One, One, Zero, Zero],
        [Zero, Zero, One, Zero],
        [Zero, One, One, One],
        [One, Zero, Zero, Zero],
        [Zero, Zero, One, Zero],
        [Zero, One, Zero, Zero],
        [One, One, One, Zero],
    ],
    [
        [Zero, Zero, One, Zero],
        [One, One, One, Zero],
        [One, One, Zero, Zero],
        [One, Zero, One, One],
        [Zero, One, Zero, Zero],
        [Zero, Zero, One, Zero],
        [Zero, Zero, Zero, One],
        [One, One, Zero, Zero],
        [Zero, One, One, One],
        [Zero, One, Zero, Zero],
        [One, Zero, One, Zero],
        [Zero, One, One, One],
        [One, Zero, One, One],
        [One, One, Zero, One],
        [Zero, One, One, Zero],
        [Zero, Zero, Zero, One],
        [One, Zero, Zero, Zero],
        [Zero, One, Zero, One],
        [Zero, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [Zero, Zero, One, One],
        [One, One, One, One],
        [One, One, One, One],
        [One, Zero, One, Zero],
        [One, One, Zero, One],
        [Zero, Zero, One, One],
        [Zero, Zero, Zero, Zero],
        [One, Zero, Zero, One],
        [One, One, One, Zero],
        [One, Zero, Zero, Zero],
        [One, Zero, Zero, One],
        [Zero, One, One, Zero],
        [Zero, One, Zero, Zero],
        [One, Zero, One, One],
        [Zero, Zero, One, Zero],
        [One, Zero, Zero, Zero],
        [Zero, Zero, Zero, One],
        [One, One, Zero, Zero],
        [One, Zero, One, One],
        [Zero, One, One, One],
        [One, Zero, One, Zero],
        [Zero, Zero, Zero, One],
        [One, One, Zero, One],
        [One, One, One, Zero],
        [Zero, One, One, One],
        [Zero, Zero, One, Zero],
        [One, Zero, Zero, Zero],
        [One, One, Zero, One],
        [One, One, One, One],
        [Zero, One, One, Zero],
        [One, Zero, Zero, One],
        [One, One, One, One],
        [One, One, Zero, Zero],
        [Zero, Zero, Zero, Zero],
        [Zero, One, Zero, One],
        [One, Zero, Zero, One],
        [Zero, One, One, Zero],
        [One, Zero, One, Zero],
        [Zero, Zero, One, One],
        [Zero, One, Zero, Zero],
        [Zero, Zero, Zero, Zero],
        [Zero, One, Zero, One],
        [One, One, One, Zero],
        [Zero, Zero, One, One],
    ],
    [
        [One, One, Zero, Zero],
        [One, Zero, One, Zero],
        [Zero, Zero, Zero, One],
        [One, One, One, One],
        [One, Zero, One, Zero],
        [Zero, One, Zero, Zero],
        [One, One, One, One],
        [Zero, Zero, One, Zero],
        [One, Zero, Zero, One],
        [Zero, One, One, One],
        [Zero, Zero, One, Zero],
        [One, One, Zero, Zero],
        [Zero, One, One, Zero],
        [One, Zero, Zero, One],
        [One, Zero, Zero, Zero],
        [Zero, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [Zero, One, One, Zero],
        [One, One, Zero, One],
        [Zero, Zero, Zero, One],
        [Zero, Zero, One, One],
        [One, One, Zero, One],
        [Zero, One, Zero, Zero],
        [One, One, One, Zero],
        [One, One, One, Zero],
        [Zero, Zero, Zero, Zero],
        [Zero, One, One, One],
        [One, Zero, One, One],
        [Zero, One, Zero, One],
        [Zero, Zero, One, One],
        [One, Zero, One, One],
        [One, Zero, Zero, Zero],
        [One, Zero, Zero, One],
        [Zero, One, Zero, Zero],
        [One, One, One, Zero],
        [Zero, Zero, One, One],
        [One, One, One, One],
        [Zero, Zero, One, Zero],
        [Zero, One, Zero, One],
        [One, One, Zero, Zero],
        [Zero, Zero, One, Zero],
        [One, Zero, Zero, One],
        [One, Zero, Zero, Zero],
        [Zero, One, Zero, One],
        [One, One, Zero, Zero],
        [One, One, One, One],
        [Zero, Zero, One, One],
        [One, Zero, One, Zero],
        [Zero, One, One, One],
        [One, Zero, One, One],
        [Zero, Zero, Zero, Zero],
        [One, One, One, Zero],
        [Zero, One, Zero, Zero],
        [Zero, Zero, Zero, One],
        [One, Zero, One, Zero],
        [Zero, One, One, One],
        [Zero, Zero, Zero, One],
        [Zero, One, One, Zero],
        [One, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [One, Zero, One, One],
        [One, Zero, Zero, Zero],
        [Zero, One, One, Zero],
        [One, One, Zero, One],
    ],
    [
        [Zero, One, Zero, Zero],
        [One, One, Zero, One],
        [One, Zero, One, One],
        [Zero, Zero, Zero, Zero],
        [Zero, Zero, One, Zero],
        [One, Zero, One, One],
        [One, One, One, Zero],
        [Zero, One, One, One],
        [One, One, One, One],
        [Zero, One, Zero, Zero],
        [Zero, Zero, Zero, Zero],
        [One, Zero, Zero, One],
        [One, Zero, Zero, Zero],
        [Zero, Zero, Zero, One],
        [One, One, Zero, One],
        [One, Zero, One, Zero],
        [Zero, Zero, One, One],
        [One, One, One, Zero],
        [One, One, Zero, Zero],
        [Zero, Zero, One, One],
        [One, Zero, Zero, One],
        [Zero, One, Zero, One],
        [Zero, One, One, One],
        [One, One, Zero, Zero],
        [Zero, One, Zero, One],
        [Zero, Zero, One, Zero],
        [One, Zero, One, Zero],
        [One, One, One, One],
        [Zero, One, One, Zero],
        [One, Zero, Zero, Zero],
        [Zero, Zero, Zero, One],
        [Zero, One, One, Zero],
        [Zero, Zero, Zero, One],
        [Zero, One, One, Zero],
        [Zero, One, Zero, Zero],
        [One, Zero, One, One],
        [One, Zero, One, One],
        [One, One, Zero, One],
        [One, One, Zero, One],
        [One, Zero, Zero, Zero],
        [One, One, Zero, Zero],
        [Zero, Zero, Zero, One],
        [Zero, Zero, One, One],
        [Zero, One, Zero, Zero],
        [Zero, One, One, One],
        [One, Zero, One, Zero],
        [One, One, One, Zero],
        [Zero, One, One, One],
        [One, Zero, One, Zero],
        [One, Zero, Zero, One],
        [One, One, One, One],
        [Zero, One, Zero, One],
        [Zero, One, One, Zero],
        [Zero, Zero, Zero, Zero],
        [One, Zero, Zero, Zero],
        [One, One, One, One],
        [Zero, Zero, Zero, Zero],
        [One, One, One, Zero],
        [Zero, One, Zero, One],
        [Zero, Zero, One, Zero],
        [One, Zero, Zero, One],
        [Zero, Zero, One, One],
        [Zero, Zero, One, Zero],
        [One, One, Zero, Zero],
    ],
    [
        [One, One, Zero, One],
        [Zero, Zero, Zero, One],
        [Zero, Zero, One, Zero],
        [One, One, One, One],
        [One, Zero, Zero, Zero],
        [One, One, Zero, One],
        [Zero, One, Zero, Zero],
        [One, Zero, Zero, Zero],
        [Zero, One, One, Zero],
        [One, Zero, One, Zero],
        [One, One, One, One],
        [Zero, Zero, One, One],
        [One, Zero, One, One],
        [Zero, One, One, One],
        [Zero, Zero, Zero, One],
        [Zero, One, Zero, Zero],
        [One, Zero, One, Zero],
        [One, One, Zero, Zero],
        [One, Zero, Zero, One],
        [Zero, One, Zero, One],
        [Zero, Zero, One, One],
        [Zero, One, One, Zero],
        [One, One, One, Zero],
        [One, Zero, One, One],
        [Zero, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [Zero, Zero, Zero, Zero],
        [One, One, One, Zero],
        [One, One, Zero, Zero],
        [One, Zero, Zero, One],
        [Zero, One, One, One],
        [Zero, Zero, One, Zero],
        [Zero, One, One, One],
        [Zero, Zero, One, Zero],
        [One, Zero, One, One],
        [Zero, Zero, Zero, One],
        [Zero, One, Zero, Zero],
        [One, One, One, Zero],
        [Zero, Zero, Zero, One],
        [Zero, One, One, One],
        [One, Zero, Zero, One],
        [Zero, One, Zero, Zero],
        [One, One, Zero, Zero],
        [One, Zero, One, Zero],
        [One, One, One, Zero],
        [One, Zero, Zero, Zero],
        [Zero, Zero, One, Zero],
        [One, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [One, One, One, One],
        [Zero, One, One, Zero],
        [One, One, Zero, Zero],
        [One, Zero, One, Zero],
        [One, Zero, Zero, One],
        [One, One, Zero, One],
        [Zero, Zero, Zero, Zero],
        [One, One, One, One],
        [Zero, Zero, One, One],
        [Zero, Zero, One, One],
        [Zero, One, Zero, One],
        [Zero, One, Zero, One],
        [Zero, One, One, Zero],
        [One, Zero, Zero, Zero],
        [One, Zero, One, One],
    ],
];
